apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kksvoil
  title: kksvoil Developer Portal
  description: fdsfsc
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: user:default/guest

